name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      
    - name: Zip Repository and Rename
      run: |
        git archive -o simhubdash.zip HEAD
        mv simhubdash.zip R3ERaceDash.simhubdash

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: r3eRaceDash
        path: R3ERaceDash.simhubdash

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: r3eRaceDash
        path: .

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: latest
        release_name: Release name RENAME!
        body: |
          **Feature**

          **Bugfix**

        draft: true
        prerelease: false

    - name: Upload Release Asset Dash board
      id: upload-release-asset-dash-board
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "R3ERaceDash.simhubdash"
        asset_name: "R3ERaceDash.simhubdash"
        asset_content_type: application/zip

